### ISSUE TITLE
Please check all javascript examples in your wiki documentation

### ISSUE THREAD

**Issue by gncgroup** [binary-com/websockets-api#12]
Start from that:
https://github.com/binary-com/websockets-api/wiki/Sending-and-Receiving-Messages
You need to wait until a connection is established. 
Otherwise, the requests will not be sent.
                                                                                Best regards Your Captain Obvious.

**Comment by borisyankov** [comment]
Thanks for pointing this out, Victor.
Have a look at 
https://github.com/binary-com/binary-live-api
It handles this case, by buffering any api calls while not yet connected/disconnected and then sending them once connection is established.

**Comment by gncgroup** [comment]
OK, thanks. 
Sorry for being rude.
